name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Create build directory
        run: mkdir -p build

      - name: Run tests
        run: go test ./...

      - name: Build Linux binary
        run: |
          GOOS=linux GOARCH=amd64 \
            go build -o build/watsontcp-go-linux-amd64 .

      - name: Build Windows binary
        run: |
          GOOS=windows GOARCH=amd64 \
            go build -o build/watsontcp-go-windows-amd64.exe .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: build/*
